# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excluir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(224, 135)
        Dialog.setStyleSheet("f")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.texto = QtWidgets.QLabel(Dialog)
        self.texto.setAlignment(QtCore.Qt.AlignCenter)
        self.texto.setWordWrap(True)
        self.texto.setObjectName("texto")
        self.verticalLayout.addWidget(self.texto)
        self.nomeLabel = QtWidgets.QLabel(Dialog)
        self.nomeLabel.setStyleSheet("font: bold;")
        self.nomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nomeLabel.setWordWrap(True)
        self.nomeLabel.setObjectName("nomeLabel")
        self.verticalLayout.addWidget(self.nomeLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Item"))
        self.texto.setText(_translate("Dialog", "Tem certeza que deseja excluir o item a seguir?"))
        self.nomeLabel.setText(_translate("Dialog", "nome"))
