# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'férias.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 267)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.inCioLabel = QtWidgets.QLabel(Dialog)
        self.inCioLabel.setObjectName("inCioLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inCioLabel)
        self.inicioDateEdit = QtWidgets.QDateEdit(Dialog)
        self.inicioDateEdit.setObjectName("inicioDateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inicioDateEdit)
        self.fimLabel = QtWidgets.QLabel(Dialog)
        self.fimLabel.setObjectName("fimLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fimLabel)
        self.fimDateEdit = QtWidgets.QDateEdit(Dialog)
        self.fimDateEdit.setObjectName("fimDateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fimDateEdit)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.botaoAdd = QtWidgets.QPushButton(Dialog)
        self.botaoAdd.setObjectName("botaoAdd")
        self.verticalLayout.addWidget(self.botaoAdd)
        self.botaoRemover = QtWidgets.QPushButton(Dialog)
        self.botaoRemover.setObjectName("botaoRemover")
        self.verticalLayout.addWidget(self.botaoRemover)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Item"))
        self.inCioLabel.setText(_translate("Dialog", "Início: "))
        self.fimLabel.setText(_translate("Dialog", "Fim:"))
        self.botaoAdd.setText(_translate("Dialog", "Adicionar"))
        self.botaoRemover.setText(_translate("Dialog", "Remover"))
        self.treeWidget.headerItem().setText(1, _translate("Dialog", "2"))
        self.treeWidget.headerItem().setText(2, _translate("Dialog", "3"))
        self.pushButton.setText(_translate("Dialog", "ok"))
